config/routes.rb
Rails.application.routes.draw do
  resources :realtors, only: [:index]
  namespace :realtors do
    resources :search, only: [:index]
  end

  root 'realtors/search#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/realtor.rb
class Realtor < ApplicationRecord
  def self.search_by_first_name(first_name)
    if first_name.present?
      where("first_name ILIKE ?", "%#{first_name}%")
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/realtors/search_controller.rb
class Realtors::SearchController < ApplicationController
  def index
    @realtors = Realtor.search_by_first_name(params[:first_name])
                       .order(:first_name)
                       .paginate(page: params[:page], per_page: 20)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("realtors_list", partial: "realtors/realtors_list", locals: { realtors: @realtors })
      end
      format.html { render "realtors/index" }
    end
  end
end

app/controllers/realtors_controller.rb
class RealtorsController < ApplicationController
  def index
    @realtors = Realtor.order(:first_name).paginate(page: params[:page], per_page: 20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/realtors_helper.rb
module RealtorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtorsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/realtors/_form.html.erb
<%= form_with(model: realtor) do |form| %>
  <% if realtor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(realtor.errors.count, "error") %> prohibited this realtor from being saved:</h2>

      <ul>
        <% realtor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :brokerage, style: "display: block" %>
    <%= form.text_field :brokerage %>
  </div>

  <div>
    <%= form.label :zipcode, style: "display: block" %>
    <%= form.number_field :zipcode %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/realtors/_realtor.html.erb
<div id="<%= dom_id realtor %>">
  <p>
    <strong>First name:</strong>
    <%= realtor.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= realtor.last_name %>
  </p>

  <p>
    <strong>Brokerage:</strong>
    <%= realtor.brokerage %>
  </p>

  <p>
    <strong>Zipcode:</strong>
    <%= realtor.zipcode %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= realtor.image_url %>
  </p>

</div>

app/views/realtors/edit.html.erb
<h1>Editing realtor</h1>

<%= render "form", realtor: @realtor %>

<br>

<div>
  <%= link_to "Show this realtor", @realtor %> |
  <%= link_to "Back to realtors", realtors_path %>
</div>

app/views/realtors/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Boston Realtors</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
  </head>
  <body class="bg-gray-100 items-center justify-center">
    <div class="flex min-h-screen items-center justify-center bg-white w-full">
      <div class="flex flex-col items-center p-6 w-full max-w-4xl mx-auto">
        <h1 class="text-3xl font-semibold text-blue-gray-900 my-4 text-center">Boston Realtors</h1>
        <div class="w-full text-left">
          <%= form_with url: realtors_search_index_path, method: :get, local: true, data: { controller: "search", action: "input->search#search" } do |form| %>
            <div class="mb-4">
              <%= form.text_field :first_name, value: params[:first_name], placeholder: "Search by First Name", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", data: { action: "input->search#search" } %>
            </div>
          <% end %>
        </div>
        <%= render partial: "realtors/search/realtors_list", locals: { realtors: @realtors } %>
      </div>
    </div>
  </body>
</html>

app/views/realtors/new.html.erb
<h1>New realtor</h1>

<%= render "form", realtor: @realtor %>

<br>

<div>
  <%= link_to "Back to realtors", realtors_path %>
</div>

app/views/realtors/search/_realtors_list.html.erb
<%= turbo_frame_tag "realtors_list" do %>
    <table class="w-full min-w-max table-auto text-left">
        <thead>
            <tr>
            <th class="border-y border-blue-gray-100 bg-blue-gray-50/50 p-4">
                <p class="block antialiased font-sans text-sm text-blue-gray-900 font-bold leading-none opacity-70">Profile photo</p>
            </th>
            <th class="border-y border-blue-gray-100 bg-blue-gray-50/50 p-4">
                <p class="block antialiased font-sans text-sm text-blue-gray-900 font-bold leading-none opacity-70">First name</p>
            </th>
            <th class="border-y border-blue-gray-100 bg-blue-gray-50/50 p-4">
                <p class="block antialiased font-sans text-sm text-blue-gray-900 font-bold leading-none opacity-70">Last name</p>
            </th>
            <th class="border-y border-blue-gray-100 bg-blue-gray-50/50 p-4">
                <p class="block antialiased font-sans text-sm text-blue-gray-900 font-bold leading-none opacity-70">Brokerage</p>
            </th>
            <th class="border-y border-blue-gray-100 bg-blue-gray-50/50 p-4">
                <p class="block antialiased font-sans text-sm text-blue-gray-900 font-bold leading-none opacity-70">Zip Code</p>
            </th>
            </tr>
        </thead>
        <tbody>
            <% @realtors.each do |realtor| %>
            <tr>
            <td class="p-4 border-b border-blue-gray-50">
                <div class="flex items-center justify-center gap-3">
                <img src="<%= realtor.image_url %>" alt="<%= realtor.first_name %>" class="inline-block relative object-center !rounded-full w-12 h-12 rounded-lg bg-blue-gray-50/50 object-contain p-1">
                </div>
            </td>
            <td class="p-4 border-b border-blue-gray-50">
                <p class="block antialiased font-sans text-sm leading-normal text-blue-gray-900 font-normal"><%= realtor.first_name %></p>
            </td>
            <td class="p-4 border-b border-blue-gray-50">
                <p class="block antialiased font-sans text-sm leading-normal text-blue-gray-900 font-normal"><%= realtor.last_name %></p>
            </td>
            <td class="p-4 border-b border-blue-gray-50">
                <p class="block antialiased font-sans text-sm leading-normal text-blue-gray-900 font-normal"><%= realtor.brokerage %></p>
            </td>
            <td class="p-4 border-b border-blue-gray-50">
                <p class="block antialiased font-sans text-sm leading-normal text-blue-gray-900 font-normal"><%= realtor.zipcode %></p>
            </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <% if @realtors.total_pages > 1 %>
        <div class="apple_pagination w-full">
            <%= will_paginate @realtors, class: 'flex justify-center gap-4' %>
        </div>
    <% end %>
<% end %>

app/views/realtors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @realtor %>

<div>
  <%= link_to "Edit this realtor", edit_realtor_path(@realtor) %> |
  <%= link_to "Back to realtors", realtors_path %>

  <%= button_to "Destroy this realtor", @realtor, method: :delete %>
</div>